# --- Configurações Gerais ---
spring.application.name=gpe
spring.profiles.active=dev
server.port=8080

# Contexto da Aplicação (http://localhost:8080/gpe)
server.servlet.context-path=/gpe
server.error.whitelabel.enabled=false

# --- Banco de Dados H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:alunos
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ruth
spring.datasource.password=

# Inicialização do JPA
spring.jpa.defer-datasource-initialization=true

# --- Configuração do Google OAuth 2.0 ---
# Atenção: No arquivo .properties, você deve escrever o caminho completo da chave
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/gpe/login/oauth2/code/google

# (Opcional) Configuração para validar tokens se você usar Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com